# /etc/keepalived/keepalived.conf
# Node: DC1 VM2
# Role: BACKUP 1

global_defs {
    router_id DC1_VM2
    enable_script_security
    script_user root
}

vrrp_script check_nginx {
    script   "/etc/keepalived/scripts/check_nginx.sh"
    interval 2
    weight   -30
    fall     2
    rise     2
}

vrrp_instance VI_1 {
    state             BACKUP
    interface         CHANGE_ME_INTERFACE
    virtual_router_id 51
    priority          150
    advert_int        1
    nopreempt

    authentication {
        auth_type PASS
        auth_pass CHANGE_ME_VRRP_SECRET
    }

    virtual_ipaddress {
        CHANGE_ME_VIP/24 dev CHANGE_ME_INTERFACE
    }

    track_script {
        check_nginx
    }

    notify /etc/keepalived/scripts/notify.sh
}

virtual_server CHANGE_ME_VIP 8080 {
    delay_loop     5
    lb_algo        lc
    lb_kind        DR
    protocol       TCP

    real_server CHANGE_ME_VM1_IP 8080 {
        weight             1
        inhibit_on_failure
        HTTP_GET {
            url {
                path        /nginx-health
                status_code 200
            }
            connect_timeout   3
            nb_get_retry      3
            delay_before_retry 2
        }
    }

    real_server CHANGE_ME_VM2_IP 8080 {
        weight             1
        inhibit_on_failure
        HTTP_GET {
            url {
                path        /nginx-health
                status_code 200
            }
            connect_timeout   3
            nb_get_retry      3
            delay_before_retry 2
        }
    }

    real_server CHANGE_ME_VM3_IP 8080 {
        weight             1
        inhibit_on_failure
        HTTP_GET {
            url {
                path        /nginx-health
                status_code 200
            }
            connect_timeout   3
            nb_get_retry      3
            delay_before_retry 2
        }
    }

    real_server CHANGE_ME_VM4_IP 8080 {
        weight             1
        inhibit_on_failure
        HTTP_GET {
            url {
                path        /nginx-health
                status_code 200
            }
            connect_timeout   3
            nb_get_retry      3
            delay_before_retry 2
        }
    }
}
